### ISSUE TITLE
Login ao dar vtex watch

### ISSUE THREAD

**Issue by augustocb** [vtex-apps/docs#11]
Não encontrei nada falando sobre a necessidade de logar.

**Comment by augustocb** [comment]
@brenoc @tamorim é possível um cenário em que uma pessoa que ainda não desenvolve para na plataforma VTEX chega até aí e não sabe que login é esse?

Talvez seja interessante dar um caminho pra que essa pessoa consiga registrar um login.

**Comment by brenoc** [comment]
É possível, @augustocb. A gente ainda não tem auto sign up, então talvez seja interessante colocar algum email de contato.
