### ISSUE TITLE
Atualizar instruções do Toolbelt

### ISSUE THREAD

**Issue by brenoc** [vtex-apps/docs#15]
Com o lançamento da versão v0.10.0, o Toolbelt mudou a sua forma de uso. O guia deve estar atualizado com essa nova forma.

**Comment by brenoc** [comment]
Acho que poderia ter tirado todo esse capítulo: https://github.com/vtex-apps/docs/blob/master/guia/1-primeiros-passos.md#workspaces-e-sandbox

A gente ensina algo que o cara nem vai usar. Não vale a pena encher a cabeça dele com esse tipo de informação.

**Comment by tamorim** [comment]
Até concordo que pro guia possa não ser necessário, mas essa informação é importante pra compreensão do modelo.
Tem algum lugar que ela está/estaria?
