### ISSUE TITLE
Nome da conta deve continua como basedevmkp?

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/docs#19]
Precisamos saber para referenciar o account name certo no doc.

\+ @brenoc @tamorim @bellacorbo

**Comment by brenoc** [comment]
@dfosco boa! tem que mudar pra `dreamstore`

**Comment by henriquesosa** [comment]
@brenoc não vale a pena mudar para um nome mais genérico? Assim acho que o guia servirá para qualquer implantação.

**Comment by brenoc** [comment]
@henriquesosa pode ser. Algo do tipo `minhaloja`? Tem alguma outra sugestão?

**Comment by henriquesosa** [comment]
@brenoc pensei exatamente nisso, ou algo como yourstore. Vou fazer um pull request com isso.
