### ISSUE TITLE
[Conceito] product-page-wrapper

### ISSUE THREAD

**Issue by tamorim** [vtex-apps/docs#22]
> I think that the documentation must make clear that it's only a utility, not a MUST use.
It's good for the sense of freedom, you know? And he can always base himself on the wrapper if he wants to go nuts I guess...

**Comment by brenoc** [comment]
@tamorim If it's optional, I think is more apropriate to open this issue here: https://github.com/vtex-apps/product-page-wrapper. This way, the docs don't get bloated with unnecessary information.
What do you think?

**Comment by dfosco** [comment]
Add concept article for it, referencing the original repo.
