### ISSUE TITLE
[Conceito] vtex-ignore

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/docs#23]
Explicar funcionamento do .vtexignore mais a fundo

**Comment by tamorim** [comment]
@dfosco Acho desnecessário, a maneiro como é descrito na intro já diz tudo que o .vtexignore é, ele é algo ridiculamente simples mesmo. Talvez a única coisa que precise é referenciar algum artigo sobre .gitignore, já que eles são similares...

**Comment by dfosco** [comment]
@tamorim Pode ser! Vamos adicionar a referência — eu por exemplo sei como funciona, mas não sei a sintaxe exata para adicionar arquivos e pastas ao ignore. Se for igual ao do Git referenciamos e _done_!

**Comment by tamorim** [comment]
@dfosco https://git-scm.com/docs/gitignore
Acho que a parte de `Pattern Format` ilustra bem o caso do `.vtexignore`

**Comment by dfosco** [comment]
<https://git-scm.com/docs/gitignore#_pattern_format> :ok_hand:

**Comment by tamorim** [comment]
@dfosco ótimo, tava tentando linkar só essa parte hehe

**Comment by dfosco** [comment]
Fixed by 2fd43aca8d08a0adcfab47df127a61b448f2db75
