### ISSUE TITLE
[Review] Intro

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/docs#24]
Technical review for [Intro](https://github.com/vtex-apps/docs/tree/refactor/new-docs/0_intro) folder (on branch `refactor/new-docs`).

 - [x] 1-REVIEW-setup-inicial.md
 - [x] 2-REVIEW-ambiente-de-desenvolvimento.md
 - [x] 3-REVIEW-criando-sua-primeira-app.md

**Comment by tamorim** [comment]
![image](https://cloud.githubusercontent.com/assets/5040487/11485242/6128f0cc-9799-11e5-8352-ecfd52d13e11.png)

@dfosco I believe that's a little strange to reference as 'Sandbox' (capital S). It feels a little proprietary, I dunno...

**Comment by tamorim** [comment]
![image](https://cloud.githubusercontent.com/assets/5040487/11485277/96115310-9799-11e5-8280-1e5dadd72c93.png)

@dfosco s/Sanbox/Sandbox

**Comment by dfosco** [comment]
Fixed by a6a840bbbfb3064a9068629e7213c70f2f10de5e

**Comment by tamorim** [comment]
@dfosco Broken Links on **2** and a I think that on the **Toolbelt** documentation link, it should point to the github repo.

**Comment by dfosco** [comment]
@tamorim Could you point this on the PR?

**Comment by tamorim** [comment]
@dfosco done

**Comment by dfosco** [comment]
@tamorim All addressed in the PR, will close when it's merged
