### ISSUE TITLE
LESS does not recognize parent selector with & if it has data-attr

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/docs#27]
Test it and add disclaimer to CSS documentation

**Comment by brenoc** [comment]
I think this does shouldn't be in the Storefront docs, since it doesn't concern it.

**Comment by dfosco** [comment]
@brenoc This is where I found the bug — it's more of a to-do to remember the
issue

> On Dec 10 2015, at 10:39 pm, Breno Calazans &lt;notifications@github.com&gt;
wrote:  

>

> Closed [#27](https://github.com/vtex-apps/docs/issues/27 "LESS does not
recognize parent selector with & if it has data-attr" ).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/vtex-ap
ps/docs/issues/27#event-488854911).![](https://github.com/notifications/beacon
/ADFI7ZvgoPTGUrGg5Wt5VXgzL1s9trFhks5pOhLDgaJpZM4Gsnqv.gif)

**Comment by dfosco** [comment]
@brenoc Where should a generic bug that affects all repos be listed?

**Comment by brenoc** [comment]
@dfosco This bug only affects LESS developers, this is not a Storefront bug or anything. So it should be on LESS docs.
