### ISSUE TITLE
Add installation of babel-preset-react

### ISSUE THREAD

**Issue by tamorim** [vtex-apps/docs#30]
On `primeiros-passos/componente-react` the command issued with the `babel-cli` will not work for transforming the 'jsx'.

We need to add the installation of [babel-preset-react](https://www.npmjs.com/package/babel-preset-react) and update the command to:
`babel --presets react *.jsx --out-dir .`

**Comment by queirozfcom** [comment]
@amoreira acho que já pode fechar esse?

**Comment by amoreira** [comment]
@queirozfcom sim!
