### ISSUE TITLE
Caminho para os executáveis nodejs após a instalação

### ISSUE THREAD

**Issue by queirozfcom** [vtex-apps/docs#35]
Eu estou fazendo o tutorial numa máquina linux e acho que o comando `babel` não é adicionado à `$PATH` quando vc instala o babel usando `npm install` local. No linux o comando é:

```
$ node_modules/.bin/babel ./storefront/assets/**.jsx --out-dir .
```
Para compilar o arquivo do tutorial.

**Comment by amoreira** [comment]
Closes https://github.com/vtex-apps/docs/pull/34
