### ISSUE TITLE
Exemplo de package.json já não é mais o que é usado no storefont-theme

### ISSUE THREAD

**Issue by queirozfcom** [vtex-apps/docs#41]
Na página [primeiros-passos/package](https://vtex-apps.github.io/docs/pt-BR/primeiros-passos/package.html), está dizendo que o `package.json` informado é o usado pelo storefront-theme mas acho que isso já não é mais o caso, o package.json do theme tem várias outras coisas - será que não é melhor apresentar aquele `package.json` como um exemplo mínimo em vezx de dizer que é o usado pelo theme?

**Comment by amoreira** [comment]
@queirozfcom sim, faz sentido. Acho que isso é herança de uma documentação mais antiga.
