### ISSUE TITLE
Instrução para rodar o babel não funciona como está na documentação

### ISSUE THREAD

**Issue by gkozlowaski** [vtex-apps/docs#47]
O comando para transpilar o arquivo na documentação usando somente `babel ./storefront/assets/**.jsx --out-dir .` não funciona, é necessário utilizar `./node_modules/.bin/babel ./storefront/assets/**.jsx --out-dir .`.

**Comment by queirozfcom** [comment]
Quando eu rodei no linux foi assim tbm. Quando vc instala local no linux ele põe os executáveis nessa pastinha. Minha dúvida é se no mac e no windows tbm é assim. Acredito que no mac seja mas no windows ñ sei. Tá rodando onde @gkozlowaski ?

**Comment by brenoc** [comment]
@queirozfcom no Windows é a mesma coisa tambem,

A diferença é que antes era recomendado instalar o babel globalmente, agora sugere-se instalar localmente. Desta forma, o binário não fica no PATH, por isso de ter que usar o binário dentro de `./node_modules/.bin/`.

**Comment by brenoc** [comment]
Outra solução é colocar dentro de `scripts` do `package.json`.
Ex:

```json
{
   "name": "my-app",
   ...
   "scripts": {
     "start": "babel ./storefront/assets/**.jsx --out-dir ."
   }
}
```

Usando esta forma, é só chamar no terminal: `npm start`.

**Comment by gkozlowaski** [comment]
@queirozfcom to rodando no Linux também.

**Comment by queirozfcom** [comment]
@brenoc Eu voto em botar o caminho `node_modules/.bin/babel` em de pôr o negócio no package.json. Acho que pode parecer "mágica" e causar confusão em quem não tiver experiência com node.

**Comment by brenoc** [comment]
@queirozfcom sim, concordo! Eu so estava explicando como pode ser feito eventualmente.
