### ISSUE TITLE
Dúvidas no decorrer do processo

### ISSUE THREAD

**Issue by leandrooriente** [vtex-apps/docs#6]
## Interface de workspaces

Para que servem os botões da direita da lista? A lixeira deleta o workspace e a seta promove? Não ficou muito claro. 

<img width="764" alt="screen shot 2015-10-22 at 10 45 08 am" src="https://cloud.githubusercontent.com/assets/1781007/10665472/303ee650-78aa-11e5-8095-e74aafef3340.png">

**Comment by brenoc** [comment]
@leandrooriente acertou! Está claro pelo jeito

**Comment by leandrooriente** [comment]
Uma tooltip ou talvez uma label tornaria mais claro.

Fiquei catando como "ativar" o workspace e quase cliquei na seta por engano.

**Comment by brenoc** [comment]
Criei no repo da gallery-ui https://github.com/vtex/gallery-ui/issues/4
