### ISSUE TITLE
Explicar melhor Workspace

### ISSUE THREAD

**Issue by augustocb** [vtex-apps/docs#9]
> Vá até o admin de workspaces, clique em "Novo workspace" e crie um workspace com o seu nome todo em letras minúsculas, sem espaços ou acentuações.

Achei essa parte bem mal explicada. Por que tem essas regras?

**Comment by brenoc** [comment]
Vou fechar essa issue, pois devido as mudanças no Toolbelt, o usuário não precisa mais saber sobre workspaces.
